spring.application.name=smartinterviewportal

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d772ohfafjfc73e6edu0-a.singapore-postgres.render.com:5432/smart_interview_db_nx88}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:smart_interview_db_nx88_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:qWO2CvWLlO8C1LXNtW70DILEGoB4BwEJ}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:10000}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}

ai.groq.api-key=${GROQ_API_KEY:}
ai.groq.model=${GROQ_MODEL:llama3-8b-8192}
